name: Build and Push Docker Image
on:
  push:
    branches:
      - master

jobs:
  BuildPush:
    name: Buildpush
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.PANCAKE }}
          image-name: frontend-docuwiki
          image-tag: latest
